### ISSUE TITLE
u-in-reply-to outside of e-content

### ISSUE THREAD

**Issue by yanick** [jmacdotorg/whim#51]
I'm very new to webmentions, so it's possible that I'm being a doofus.

If I look at https://indieweb.org/reply, a reply can look like

```
<div class="h-entry">
 <a class="p-author h-card" href="http://mysite.example.org">
   <img alt="" src="http://mysite.example.org/icon.jpg"/>
   Supercool Indiewebauthor</a>: 
 in reply to:
 <a href="http://example.com/note123" class="u-in-reply-to">Some note with a point</a>
 <div class="p-name p-content">Good point! Now what is the next thing we should do?</div>
</div>

```

yet, if we look at  https://github.com/jmacdotorg/whim/blob/55adf1cafcff239c3d0daac8f65a907f3a6db4bc/lib/Whim/Mention.pm#L32, it looks like the in-reply-to needs to be within the e-content to be seen. Shouldn't the 'h-entry' be passed to `new_from_html` instead?

**Comment by jmacdotorg** [comment]
You're absolutely correct -- in fact, had a conversation with the folks in #indieweb-dev about this just a few hours before you asked, because I had similar suspicions that Whim's style isn't quite right.

I wanted to know if Whim should just check for `h-entry`, just as you suggest here, and for the same reasons. But then @snarfed -- who has worked with webmentions *much* more extensively than I -- said this:

> wms are expected to be idempotent, there's generally no harm in sending/resending them too widely

This would imply that Whim is unnecessarily trying to second-guess the user here, and its best course of action is to just lift this "cleverness" and just throw webmentions at every valid hyperlink at the given URL, putting the burden of handling on the receiver.

I am currently leaning towards this solution as the default behavior for calling `whim send` with one argument, and leaving room for adjusting this behavior (e.g. limiting the seeing to `h-entry` content) depending upon command-line options.

What do you think?

**Comment by yanick** [comment]
Inasmuch as I'm a noob who haven't truly pored over the specs yet, that makes sense to me.

 I think it's better to err on the side of sending too much rather than too little. At first I was wary and thought that'd be noisy waste. But, as you said, the calls are supposed to be idempotent, so the effort to receive them and say "saw that already, thanks!" is small. Plus the overall traffic generated by webmentions is very small and very sporadic. And -- and that's the important part for me -- sending it many times can be useful in case the webmentionee didn't catch the webmention the first time around. 

So, yeah, implementation-wise, I think a sane base behavior would be to gather all `h-entry`s in the document, and for each of them broadcast to all `u-in-reply-to`s found inside.

**Comment by jmacdotorg** [comment]
In fact, the base behavior I argued for yesterday would have Whim attempt to send a webmention to *every* valid target in the source page, regardless of microformats.

One could pass in a command-line flag to say "limit this to targets found in an `h-entry`". (And "limit to `in-reply-to` properties" could be another potential flag.)

I intend to have a pull request that implements this submitted later this weekend.

**Comment by yanick** [comment]
> In fact, the base behavior I argued for yesterday would have Whim attempt to send a webmention to _every_ valid target in the source page, regardless of microformats.

Aaaah, I see....

:ponder:

:go look at the specs:

Aaaaaah, I see! It was my (wrong) assumption that the webmention sending included bits of the document. But no, we only send the source and target url. In that case, yeah, a first approach of "heck, let's broadcast it all" isn't a bad idea. 

Or if it's a bad idea, let's go on and discover why it is the interesting way. :-)
